version: '3.6'
services:
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    image: 'postgres:14.1-alpine'
    restart: always
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    environment:
      MIX_ENV: dev
    env_file:
      - .docker.dev.env
    ports:
      - '4000:4000'
    volumes:
      - .:/app
volumes:
  pgdata:
